# Generated by Django 5.0.6 on 2024-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
