# Generated by Django 5.0.6 on 2024-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_lesson_options_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='class_course',
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
