# Generated by Django 5.0.6 on 2024-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_student_id_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('information_technology', 'Information Technology'), ('computer_science', 'Computer Science')], max_length=50, null=True),
        ),
    ]
