# Generated by Django 5.0.6 on 2024-07-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_videolessoncontent_and_more'),
        ('users', '0004_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='classes.class'),
        ),
    ]
