# Generated by Django 5.0.6 on 2024-07-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_enrolled_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_class',
        ),
    ]
